# Generated by Django 2.1.5 on 2020-08-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='done',
            field=models.NullBooleanField(),
        ),
    ]
